#! /bin/sh

bspc config border_width        1
bspc config window_gap         10
bspc config top_padding        16

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor DVI-0 -d 6 7 8 9 10
bspc monitor DisplayPort1 -s DVI-0

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer floating=on

#xrandr --output DVI-0 --right-of DisplayPort-0
feh --bg-fill ~/Pictures/sea-cliff-village.jpeg
setxkbmap -option ctrl:nocaps
xautolock -time 5 -locker 'i3lock -i /home/mark/Pictures/dumpster-hot-tub.png -t -u' &
xcompmgr -c -C -t-5 -l-5 -r4.2 -o.30 &
dunst &

#panel dzen2 &
panel &
