#! /bin/sh

bspc config border_width        1
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP1-1-1 -d 1 2 3
bspc monitor DP1-1-2 -d 4 5 6
bspc monitor DVI-I-1-1 -d 7 8 9

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2

setxkbmap -option ctrl:nocaps
xautolock -time 5 -locker 'i3lock -c 000000' &
feh --bg-fill ~/Pictures/sea-cliff-village.jpeg &
xcompmgr -c -n &
dunst &

panel &
